export const DOCTORS = [
  {
    id: 1,
    name: 'Dr. Anika Sharma',
    specialization: 'Cardiologist',
    experience: 14,
    image: '/doctors/anika-sharma.jpg',
    fallbackImage: 'https://api.dicebear.com/7.x/personas/svg?seed=anika&backgroundColor=b6e3f4',
    qualification: 'MBBS, MD (Cardiology), DM',
    fee: 800,
    rating: 4.9,
    reviews: 312,
    bio: 'Specialist in interventional cardiology with expertise in echocardiography and cardiac catheterization.',
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    timeSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '04:00 PM', '04:30 PM', '05:00 PM', '05:30 PM'],
  },
  {
    id: 2,
    name: 'Dr. Rahul Mehta',
    specialization: 'Neurologist',
    experience: 11,
    image: '/doctors/rahul-mehta.jpg',
    fallbackImage: 'https://api.dicebear.com/7.x/personas/svg?seed=rahul&backgroundColor=c0aede',
    qualification: 'MBBS, MD, DM (Neurology)',
    fee: 900,
    rating: 4.8,
    reviews: 248,
    bio: 'Expert in treating epilepsy, stroke, Parkinson\'s, and other complex neurological disorders.',
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    timeSlots: ['10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM', '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM'],
  },
  {
    id: 3,
    name: 'Dr. Priya Nair',
    specialization: 'Gynecologist',
    experience: 9,
    image: '/doctors/priya-nair.jpg',
    fallbackImage: 'https://api.dicebear.com/7.x/personas/svg?seed=priya&backgroundColor=ffd5dc',
    qualification: 'MBBS, MS (Obstetrics & Gynaecology)',
    fee: 750,
    rating: 4.9,
    reviews: 421,
    bio: 'Dedicated to women\'s health with expertise in high-risk pregnancies and laparoscopic surgeries.',
    availableDays: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
    timeSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM', '04:00 PM'],
  },
  {
    id: 4,
    name: 'Dr. Suresh Kumar',
    specialization: 'Orthopedic Surgeon',
    experience: 16,
    image: '/doctors/suresh-kumar.jpg',
    fallbackImage: 'https://api.dicebear.com/7.x/personas/svg?seed=suresh&backgroundColor=d1f4d0',
    qualification: 'MBBS, MS (Orthopaedics), DNB',
    fee: 850,
    rating: 4.7,
    reviews: 185,
    bio: 'Pioneering joint replacement and sports injury management with 16+ years of surgical experience.',
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
    timeSlots: ['08:30 AM', '09:00 AM', '09:30 AM', '10:00 AM', '04:00 PM', '04:30 PM', '05:00 PM'],
  },
  {
    id: 5,
    name: 'Dr. Fatima Sheikh',
    specialization: 'Dermatologist',
    experience: 7,
    image: '/doctors/fatima-sheikh.jpg',
    fallbackImage: 'https://api.dicebear.com/7.x/personas/svg?seed=fatima&backgroundColor=ffd5dc',
    qualification: 'MBBS, MD (Dermatology)',
    fee: 700,
    rating: 4.8,
    reviews: 293,
    bio: 'Expert in cosmetic dermatology, skin cancer screening, and advanced laser treatments.',
    availableDays: ['Tuesday', 'Wednesday', 'Friday'],
    timeSlots: ['10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM', '05:00 PM', '05:30 PM', '06:00 PM'],
  },
  {
    id: 6,
    name: 'Dr. Arjun Patel',
    specialization: 'Pediatrician',
    experience: 12,
    image: '/doctors/arjun-patel.jpg',
    fallbackImage: 'https://api.dicebear.com/7.x/personas/svg?seed=arjun&backgroundColor=b6e3f4',
    qualification: 'MBBS, MD (Pediatrics), Fellowship NICU',
    fee: 650,
    rating: 4.9,
    reviews: 517,
    bio: 'Compassionate care for children from neonates to adolescents, with NICU specialization.',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    timeSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '04:00 PM', '04:30 PM', '05:00 PM'],
  },
]

export const DIAGNOSTIC_TESTS = [
  {
    id: 'blood-cbc',
    name: 'Complete Blood Count (CBC)',
    category: 'Blood Test',
    icon: '🩸',
    price: 350,
    duration: '24 hours',
    description: 'Measures red & white blood cells, hemoglobin, hematocrit, and platelets.',
    preparation: 'Fasting 8–12 hours required',
    homeCollection: true,
  },
  {
    id: 'blood-sugar',
    name: 'Blood Sugar (Fasting + PP)',
    category: 'Diabetes Panel',
    icon: '💉',
    price: 180,
    duration: '4 hours',
    description: 'Monitors glucose levels to diagnose and manage diabetes.',
    preparation: 'Fasting 8 hours required',
    homeCollection: true,
  },
  {
    id: 'thyroid-tft',
    name: 'Thyroid Function Test (TFT)',
    category: 'Thyroid Panel',
    icon: '🦋',
    price: 650,
    duration: '24 hours',
    description: 'TSH, T3, T4 levels to evaluate thyroid gland function.',
    preparation: 'Morning sample preferred',
    homeCollection: true,
  },
  {
    id: 'lipid-profile',
    name: 'Lipid Profile',
    category: 'Cardiac Panel',
    icon: '❤️',
    price: 480,
    duration: '12 hours',
    description: 'Cholesterol, triglycerides, HDL, LDL to assess cardiovascular risk.',
    preparation: 'Fasting 12 hours required',
    homeCollection: true,
  },
  {
    id: 'xray-chest',
    name: 'Chest X-Ray',
    category: 'Radiology',
    icon: '🫁',
    price: 400,
    duration: 'Same day',
    description: 'Imaging of chest cavity to detect lung and heart conditions.',
    preparation: 'Remove metal jewellery',
    homeCollection: false,
  },
  {
    id: 'xray-bone',
    name: 'Bone X-Ray',
    category: 'Radiology',
    icon: '🦴',
    price: 350,
    duration: 'Same day',
    description: 'Evaluates fractures, bone density, and joint conditions.',
    preparation: 'No special preparation',
    homeCollection: false,
  },
  {
    id: 'mri-brain',
    name: 'MRI Brain',
    category: 'MRI',
    icon: '🧠',
    price: 5500,
    duration: '24–48 hours',
    description: 'Detailed imaging of brain tissue for neurological assessment.',
    preparation: 'Remove metal implants; no food 4 hours before contrast MRI',
    homeCollection: false,
  },
  {
    id: 'mri-spine',
    name: 'MRI Spine',
    category: 'MRI',
    icon: '🦴',
    price: 6000,
    duration: '24–48 hours',
    description: 'Comprehensive spinal cord and disc evaluation.',
    preparation: 'Remove metal objects; claustrophobic patients may need sedation',
    homeCollection: false,
  },
  {
    id: 'ct-abdomen',
    name: 'CT Abdomen',
    category: 'CT Scan',
    icon: '🫀',
    price: 4200,
    duration: '12–24 hours',
    description: 'Cross-sectional imaging of abdominal organs.',
    preparation: 'Fasting 4 hours; contrast dye allergy check',
    homeCollection: false,
  },
  {
    id: 'ct-chest',
    name: 'CT Chest (HRCT)',
    category: 'CT Scan',
    icon: '🫁',
    price: 3800,
    duration: '12–24 hours',
    description: 'High-resolution imaging for lung diseases and COVID assessment.',
    preparation: 'Remove metal objects; minimal fasting',
    homeCollection: false,
  },
  {
    id: 'usg-abdomen',
    name: 'USG Abdomen & Pelvis',
    category: 'Ultrasound',
    icon: '📡',
    price: 900,
    duration: '4–6 hours',
    description: 'Non-invasive imaging of abdominal and pelvic organs.',
    preparation: 'Full bladder required; fasting 6 hours',
    homeCollection: false,
  },
  {
    id: 'urine-routine',
    name: 'Urine Routine & Microscopy',
    category: 'Urine Test',
    icon: '🧪',
    price: 150,
    duration: '4 hours',
    description: 'Detects UTI, kidney issues, and metabolic disorders.',
    preparation: 'Morning mid-stream sample preferred',
    homeCollection: true,
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Meera Krishnaswamy',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=meera',
    role: 'Patient',
    text: 'The booking process was seamlessly smooth. Dr. Sharma diagnosed my heart condition swiftly and the reports were ready the same day. Truly world-class service.',
    rating: 5,
    date: 'January 2025',
  },
  {
    id: 2,
    name: 'Rohit Agarwal',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=rohit',
    role: 'Patient',
    text: 'Home blood collection was a game-changer for my elderly mother. Professional, punctual, and the digital reports arrived within hours. Highly recommended!',
    rating: 5,
    date: 'February 2025',
  },
  {
    id: 3,
    name: 'Sunita Rao',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=sunita',
    role: 'Patient',
    text: 'MRI results were explained so clearly by Dr. Mehta. The center is equipped with the latest technology and the staff is incredibly supportive.',
    rating: 5,
    date: 'December 2024',
  },
  {
    id: 4,
    name: 'Vikram Joshi',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=vikram',
    role: 'Patient',
    text: 'Best pediatric care I could find for my son. Dr. Patel was so patient and thorough. The online booking saved us so much time at the reception.',
    rating: 5,
    date: 'March 2025',
  },
]

export const SERVICES = [
  { icon: '🫀', title: 'Cardiology', desc: 'ECG, Echo, Stress Test' },
  { icon: '🧠', title: 'Neurology', desc: 'EEG, MRI, NCV' },
  { icon: '🦷', title: 'Dental', desc: 'Scaling, X-Ray, RCT' },
  { icon: '👁️', title: 'Ophthalmology', desc: 'Vision test, Cataract' },
  { icon: '🦴', title: 'Orthopaedics', desc: 'Bone scan, Joint care' },
  { icon: '🧬', title: 'Pathology', desc: '500+ lab tests' },
  { icon: '🫁', title: 'Radiology', desc: 'X-Ray, CT, MRI, USG' },
  { icon: '🩺', title: 'General Medicine', desc: 'Check-up, Fever, Flu' },
]

export const HEALTH_PACKAGES = [
  {
    id: 'basic',
    name: 'Basic Health Check',
    price: 999,
    originalPrice: 1599,
    tests: 15,
    includes: ['CBC', 'Blood Sugar', 'Urine Routine', 'Lipid Profile', 'LFT', 'KFT'],
    popular: false,
  },
  {
    id: 'comprehensive',
    name: 'Comprehensive Package',
    price: 2499,
    originalPrice: 4200,
    tests: 38,
    includes: ['All Basic Tests', 'Thyroid Panel', 'Vitamin B12 & D3', 'HbA1c', 'Chest X-Ray', 'ECG'],
    popular: true,
  },
  {
    id: 'full-body',
    name: 'Full Body Checkup',
    price: 4999,
    originalPrice: 8500,
    tests: 72,
    includes: ['All Comprehensive Tests', 'Tumor Markers', 'Hormonal Panel', 'USG Abdomen', 'Stress Test', 'Doctor Consultation'],
    popular: false,
  },
]
